# app/config/security.yml
security:
    encoders:
        # Classe + algorithme de stockage password
        FOS\UserBundle\Model\UserInterface: bcrypt

    # Définition des rôles avec leurs rôles
    # de niveaux inférieurs
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        # Bundle responsable des utilisateurs
        # et identifiant unique.
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # Nom des règles de sécurité
        main:
            # Sur quelle partie du site cela doit s'exécuter.
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true
        default:
            anonymous: ~
            http_basic: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
