<?php

namespace ChemicalsBundle\Repository;
use ChemicalsBundle\Repository\PaginatorRepository;
/**
 * AtomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtomRepository extends PaginatorRepository
{
    public function getNonUsedAtoms()
    {
        /*$qb = $this->_em->createQueryBuilder();

        $nots = $qb->select(['mainAtom', 'atoms'])
                  ->from('ChemicalsBundle:AtomsGroup', 'cba')
                  ->getQuery()
                  ->getResult();

        $linked = $qb->select('a')
            ->from('ChemicalsBundle:Atom', 'a')
            ->where($qb->expr()->notIn('a.id', $nots))
            ->getQuery()
            ->getResult();
        
        return $this->_em->createQuery("select a from Atom a where"
                . " a.id not in (select atom_id from chemicals_bound_atoms) and "
                . "a.id not in (select main_atom_id from chemicals_atoms_group) "
                . "order by a.name");*/
        return $this->findAll();
    }
}
