<?php

namespace ChemicalsBundle\Repository;
use ChemicalsBundle\Repository\PaginatorRepository;

/**
 * ElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElementRepository extends PaginatorRepository
{
    public function getElementsOderedByNameForForms()
    {
        return $this
            ->createQueryBuilder('e')
            ->orderBy('e.name', 'ASC');
    }
}
